In [11]:
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import tensorflow as tf
from keras import datasets, utils, layers, Sequential
from keras.callbacks import TensorBoard

In [3]:
(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

print(f"train image shape={train_images.shape}, test image shape={test_images.shape}")
print(f"train label shape={train_labels.shape}, test label shape={test_labels.shape}")
# print(matplotlib.get_backend())

flatten = 28 * 28
TRAINING_SIZE = len(train_images)
TEST_SIZE = len(test_images)
# print(TRAINING_SIZE, TEST_SIZE)
trainImages = np.reshape(train_images, (TRAINING_SIZE, flatten))
testImages = np.reshape(test_images, (TEST_SIZE, flatten))
print(f"after flatten, train image shape={trainImages.shape}, test image shape={testImages.shape}")

# convert to float
trainImages = trainImages.astype(np.float32)
testImages = testImages.astype(np.float32)
# print(trainImages[0])
trainImages /= 255
testImages /= 255
# print(trainImages[0])

NUM_DIGITS = len(np.unique(train_labels))
print(f'NUM_DIGITS={NUM_DIGITS}')
trainLabels = utils.to_categorical(train_labels, NUM_DIGITS)
testILabels = utils.to_categorical(test_labels, NUM_DIGITS)
model = Sequential()
model.add(layers.Dense(256, activation=tf.nn.relu, input_shape=(flatten,)))
model.add(layers.Dense(64, activation=tf.nn.relu))
model.add(layers.Dense(10, activation=tf.nn.softmax))
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.summary()

train image shape=(60000, 28, 28), test image shape=(10000, 28, 28)
train label shape=(60000,), test label shape=(10000,)
after flatten, train image shape=(60000, 784), test image shape=(10000, 784)
NUM_DIGITS=10
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 256)               200960    
_________________________________________________________________
dense_5 (Dense)              (None, 64)                16448     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                650       
Total params: 218,058
Trainable params: 218,058
Non-trainable params: 0
_________________________________________________________________


In [12]:
tbCallback = TensorBoard(log_dir='../log', histogram_freq=True,
                         write_graph=True, write_images=True)

In [4]:
history = model.fit(trainImages, trainLabels, epochs=20, callbacks=[tbCallback])

Epoch 1/20
60000/60000 [==============================] - 5s 77us/step - loss: 0.2144 - accuracy: 0.9369
Epoch 2/20
60000/60000 [==============================] - 5s 78us/step - loss: 0.0953 - accuracy: 0.9719
Epoch 3/20
60000/60000 [==============================] - 5s 87us/step - loss: 0.0731 - accuracy: 0.9795
Epoch 4/20
60000/60000 [==============================] - 6s 93us/step - loss: 0.0575 - accuracy: 0.9848
Epoch 5/20
60000/60000 [==============================] - 8s 127us/step - loss: 0.0485 - accuracy: 0.9865
Epoch 6/20
60000/60000 [==============================] - 6s 101us/step - loss: 0.0405 - accuracy: 0.9890
Epoch 7/20
60000/60000 [==============================] - 6s 97us/step - loss: 0.0343 - accuracy: 0.9908
Epoch 8/20
60000/60000 [==============================] - 6s 94us/step - loss: 0.0330 - accuracy: 0.9918
Epoch 9/20
60000/60000 [==============================] - 7s 123us/step - loss: 0.0265 - accuracy: 0.9930
Epoch 10/20
60000/60000 [===========================

In [5]:
predictLabels = model.predict(testImages)
print(f"test marker as: {testILabels[:10]}")
print(f"predict as: {predictLabels[:10]}")

test marker as: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
predict as: [[0.0000000e+00 0.0000000e+00 1.1869781e-28 4.4912720e-23 0.0000000e+00
  0.0000000e+00 0.0000000e+00 1.0000000e+00 1.4972663e-37 2.0959193e-26]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 5.2443340e-34 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [7.9092449e-28 1.0000000e+00 1.2860488e-13 2.3166024e-18 7.9969336e-14
  5.8185011e-13 9.3789536e-15 3.2359924e-11 1.1709390e-12 1.0609890e-20]
 [1.0000000e+00 2.0426805e-32 1.0943064e-18 2.0154024e-19 4.5623499e-22
  1.8100234e-19 4.3925248e-15 1.2279282e-18 9.7572864e-24 3.1936221e-15]
 [4.0426419e-26 4.8781018e-35 3.3783017e-22 2.3257946e-32 1.0

In [6]:
loss, accuracy = model.evaluate(testImages, testILabels)
print(f'test loss={loss}, test accuracy={accuracy}')

10000/10000 [==============================] - 0s 25us/step
test loss=0.20159224009921264, test accuracy=0.9804999828338623
